name: CICD Pipeline

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Build Maven Project
      run: mvn clean package

    - name: Build Docker Image
      run: docker build -t 149536451818.dkr.ecr.ap-south-1.amazonaws.com/login:${{ github.run_number }} .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Authenticate With Amazon Elastic Container Registry
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Docker Image to Amazon Elastic Container Registry
      run: |
        docker push 149536451818.dkr.ecr.ap-south-1.amazonaws.com/login:${{ github.run_number }}

    - name: Update Docker Image Tag in Kubernetes Manifest
      run: |
        sed -i "s/Build_Tag/${{ github.run_number }}/g" Deployment.yaml

    - name: Configure Kubectl for Elastic Kubernetes Cluster
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name Amazon_Production_EKS_Cluster

    - name: Deploy Application to Elastic Kubernetes Cluster
      run: |
        kubectl delete deployment webpage-deployment -n production || true
        kubectl apply -f Deployment.yaml